
apiVersion: v1
kind: Service
metadata:
  name: savvy-ai-chatbot
  labels:
    app: savvy-ai-chatbot
spec:
  selector:
    app: savvy-ai-chatbot
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: health
    port: 8080
    targetPort: 8000
  type: ClusterIP
